spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID} 
            client-secret: ${OKTA_SECRET}
        provider:
          okta:
            issuer-uri: https://${OKTA_DOMAIN}/oauth2/default

okta:
  oauth2:
    issuer: https://dev-62765639.okta.com/oauth2/default