spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID} 
            client-secret: ${OKTA_SECRET}
        provider:
          okta:
            issuer-uri: https://${OKTA_DOMAIN}.oktapreview.com/oauth2/default
