# OKTA_CLIENT_ID=0oab8cuvb2uJYp6Mx5d6l
# OKTA_SECRET=0M7VJDYDCHP4UqaWEOjFi6Gxs_-nWD7bPTgtEkjj
# OKTA_DOMAIN=dev-62765639.okta.com

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID} 
            client-secret: ${OKTA_SECRET}
        provider:
          okta:
            issuer-uri: https://${OKTA_DOMAIN}.oktapreview.com/oauth2/default
