spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${OKTA_DOMAIN}/oauth2/default

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include=:
