spring:
  security:
    oauth2:
      resourceserver:
#        user-info-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/userinfo
        j wt:
          issuer-uri: https://${OKTA_DOMAIN}/oauth2/default

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include=:
