spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-62765639.okta.com/oauth2/default

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include=*
